"""DAC neural-codec robustness figure + table for SONAR camera-ready.

Numbers come from the rebuttal letter (no re-running):
  EER:        6.00% (clean)  ->  8.60% (DAC encode/decode)
  AUC:        0.977 (clean)  ->  0.953 (DAC)
  Spearman:   0.944 between clean and DAC scores

Outputs:
  papr_files/figures/dac_robustness.pdf
  papr_files/figures/dac_robustness_table.tex
"""
from __future__ import annotations
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO = Path(__file__).resolve().parents[1]
FIG_DIR = REPO / "papr_files" / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

EER = {"Clean": 6.00, "DAC": 8.60}
AUC = {"Clean": 0.977, "DAC": 0.953}
SPEARMAN = 0.944


def make_figure():
    fig, axes = plt.subplots(1, 2, figsize=(6.4, 2.6), constrained_layout=True)
    colors = {"Clean": "#4c72b0", "DAC": "#dd8452"}

    ax = axes[0]
    keys = ["Clean", "DAC"]
    vals = [EER[k] for k in keys]
    bars = ax.bar(keys, vals, color=[colors[k] for k in keys], edgecolor="black", linewidth=0.6)
    for b, v in zip(bars, vals):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.15, f"{v:.2f}", ha="center", va="bottom", fontsize=9)
    ax.set_ylabel("EER (%)")
    ax.set_title("In-the-Wild EER", fontsize=10)
    ax.set_ylim(0, max(vals) * 1.25)
    ax.grid(axis="y", alpha=0.3)

    ax = axes[1]
    vals = [AUC[k] for k in keys]
    bars = ax.bar(keys, vals, color=[colors[k] for k in keys], edgecolor="black", linewidth=0.6)
    for b, v in zip(bars, vals):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.001, f"{v:.3f}", ha="center", va="bottom", fontsize=9)
    ax.set_ylabel("AUC")
    ax.set_title("In-the-Wild AUC", fontsize=10)
    ax.set_ylim(0.93, 1.0)
    ax.grid(axis="y", alpha=0.3)
    ax.text(0.98, 0.04, f"Spearman $\\rho$ = {SPEARMAN:.3f}",
            transform=ax.transAxes, ha="right", va="bottom", fontsize=8,
            bbox=dict(facecolor="white", edgecolor="#ccc", boxstyle="round,pad=0.3"))

    out_pdf = FIG_DIR / "dac_robustness.pdf"
    out_png = FIG_DIR / "dac_robustness.png"
    fig.savefig(out_pdf, dpi=300)
    fig.savefig(out_png, dpi=200)
    plt.close(fig)
    print(f"PDF -> {out_pdf}")
    print(f"PNG -> {out_png}")


def make_table():
    out = FIG_DIR / "dac_robustness_table.tex"
    with open(out, "w") as f:
        f.write("% Auto-generated by bench/dac_plot.py - do not edit by hand.\n")
        f.write("\\begin{table}[t]\n\\centering\n\\small\n")
        f.write("\\caption{Robustness to neural codec post-processing on the In-the-Wild test set. "
                "SONAR-Full is evaluated zero-shot after encode-decode through the Descript Audio "
                "Codec at 16\\,kHz. The Spearman rank correlation between clean and codec-processed "
                "scores is $0.944$, indicating that relative ordering is largely preserved.}\n")
        f.write("\\label{tab:dac_robustness}\n")
        f.write("\\begin{tabular}{lcc}\n\\toprule\n")
        f.write("Condition & EER (\\%) & AUC \\\\\n\\midrule\n")
        f.write(f"Clean (no codec) & {EER['Clean']:.2f} & {AUC['Clean']:.3f} \\\\\n")
        f.write(f"DAC (encode/decode) & {EER['DAC']:.2f} & {AUC['DAC']:.3f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    print(f"TeX -> {out}")


if __name__ == "__main__":
    make_figure()
    make_table()
